### ISSUE TITLE
Bedrock token_usage is returning character count, not tokens

### ISSUE THREAD

**Issue by WayneBuckhanan** [llumiverse/llumiverse#10]
See [bedrock/index.ts](https://github.com/llumiverse/llumiverse/blob/b45056a10d297d04707a58e0deeae159409515d5/drivers/src/bedrock/index.ts#L131)

Since AWS Bedrock doesn't currently return token counts and each model may have their own tokenizer, might the short-term answer be for this return an additional property indicating it `isCharacterCount: true` or some other way of indicating this isn't actually tokens? (The default of "just knowing" based on using the Bedrock driver defeats some of the point of having a library like Llumiverse in the mix to provide a uniform interface for multiple models/providers.)

If it is of interest, I might make a pull request using the appropriate tokenizers instead of `.length`...once Anthropic releases official info on their tokenizer for Claude 3...

**Comment by WayneBuckhanan** [comment]
It appears that the Bedrock token counts are currently available in headers in an intermediate response, just not exposed to the `bedrock-runtime` JS SDK.
https://github.com/aws/aws-sdk-js-v3/issues/5917

Not sure if it is worth attempting a middleware approach like in the linked issue, but adding this here in case someone (maybe me) wants to take on that task.

**Comment by gspradlin** [comment]
> If it is of interest, I might make a pull request using the appropriate tokenizers instead of `.length`...once Anthropic releases official info on their tokenizer for Claude 3...

@WayneBuckhanan We'd welcome a pull request!

**Comment by WayneBuckhanan** [comment]
Just implemented a test-spike and was able to get the actual token counts from Bedrock this way:

```js
import { BedrockRuntimeClient, InvokeModelCommand } from "@aws-sdk/client-bedrock-runtime"
const client = new BedrockRuntimeClient({region: 'us-west-2'})
client.middlewareStack.add(next => async (args) => {
  const response = await next(args)
  const headerLeader = 'x-amzn-bedrock-'
  Object.keys(response.response.headers).forEach(header => {
    if(header.startsWith(headerLeader)) {
      response.output.$metadata[header.slice(headerLeader.length)] = response.response.headers[header]
    }
  })
  return response
})
```

**Comment by WayneBuckhanan** [comment]
Will see if I get a PR together for that before you get a chance to implement it.

**Comment by ebarroca** [comment]
We're going to look into this. We've had many conversations about what we should do with tokens
- take what the provider gives us (which is not consistent across models/providers)
- standardize on char count (so it's comparable)
- standardize on cl100k_base 

Basically use a standard model to be able to compare speed amongst models/providers or just use what the underlying provider is doing. Haven't made a decision but interested in inputs.

**Comment by WayneBuckhanan** [comment]
Personally, I need the tokens as reported by the models. I don't care that they are inconsistent between providers because whatever a given provider counts is what is relevant when using that provider since I primarily want these token counts for tracking usage and costs per LLM call. That requires provider specific token counts, no matter how they achieved that tokenization.

Using character count or some other tokenization method is great for consistency across models and I can see where it could be useful in parallel with the provider supplied usage stats, I just don't see the benefit in replacing the provider specific stats. That data is already being returned to Llumiverse by the time you would filter it (even in this odd case of Bedrock hiding that data in normally discarded headers), so I'm not sure what would be saved by not including the provider given counts as meta data alongside any other standardized counts that may be of interest.

Also, if I want to compare character counts, I can do that with a string.length call myself without needing Llumiverse to do that for me. I don't mind a helper function that takes the array of input messages and returns a character count for the whole set of input strings, but even that is just a one-liner. Same for word count if that's how I decided to compare models.

More useful to me would be having a helper function (that I can call without thinking about what model I'm using) that uses the appropriate tokenization method for the given model/provider to calculate the model-specific token count before sending it. This would be to check things like how close we are to the model's context limits to potentially limit the output max_tokens to suit. Of course, not all the models provide their tokenization algorithms right away (i.e. Anthropic for Claude 3)...

I'm really appreciating the abstraction that Llumiverse provides already and hope that perspective helps.

**Comment by LeonRuggiero** [comment]
Token usage support was added in: 

- https://github.com/llumiverse/llumiverse/pull/24

Regarding the
 >odd case of Bedrock hiding that data in normally discarded headers

These are now used by default for AWS bedrock, however when they aren't there individual model supported token usage is passed along. Though AWS bedrock mistral inconveniently can provide neither.
