### ISSUE TITLE
Cohere Command-R models have incorrect input parameters

### ISSUE THREAD

**Issue by WayneBuckhanan** [llumiverse/llumiverse#11]
Cohere Command Text and Command Text Lite work just fine.
Command R and Command R Plus error.

> Malformed input request: #: required key [message] not found#: extraneous key [prompt] is not permitted, please reformat your input and try again.

It appears the request format has changed from [Cohere Command](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-cohere-command.html) to [Cohere Command R](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-cohere-command-r-plus.html)

```json
{
    "prompt": string,
    "temperature": float,
    "p": float,
    "k": float,
    "max_tokens": int,
    "stop_sequences": [string],
    "return_likelihoods": "GENERATION|ALL|NONE",
    "stream": boolean,
    "num_generations": int,
    "logit_bias": {token_id: bias},
    "truncate": "NONE|START|END"
}
```

to

```json
{
    "message": string,
    "chat_history": [
        {
            "role":"USER or CHATBOT",
            "message": string
        }
    ],
    "documents": [
        {"title": string, "snippet": string},
    ],
    "search_queries_only" : boolean,
    "preamble" : string,
    "max_tokens": int,
    "temperature": float,
    "p": float,
    "k": float,
    "prompt_truncation" : string,
    "frequency_penalty" : float,
    "presence_penalty" : float,
    "seed" : int,
    "return_prompt" : boolean,
    "stop_sequences": [string],
    "raw_prompting" : boolean

}
```

And the returned text is now in `response.text` rather than `response.generations[0].text`.

**Comment by ebarroca** [comment]
Thanks for reporting this, we've added the support (and tests) for cohere command R.

**Comment by WayneBuckhanan** [comment]
Thank you.

When will that make it into a released npm package?
