### ISSUE TITLE
Add parameters to completion API

### ISSUE THREAD

**Issue by ebarroca** [llumiverse/llumiverse#25]
1. togetherai returns the usage token info in the last streaming event. 
We should find a way to propagate this info at the DefaultCompletionStream level to be used as usage info
2. Some providers API are return a finish reason. It should be nice to return this from driver execution and to store it in the ExecutionRun in the mongo database

## Added in ExecutionOptions 
    stop_sequence?: string | string[];
    top_k?: number;
    top_p?: number;
    top_logprobs?: number;
    presence_penalty?: number;
    frequency_penalty?: number;
    include_original_response?: boolean;

## Added in Completion
    finish_reason?: "stop" | "length" | string;
    original_response?: Record<string, any>;

Already done:
finish_reason and original_response: (only for execute)

openai
mistral
togetherai
vertexai
- gemini - OK
- palm like models doesn't support the finish_reason
replicate -> only original_response. Cannot find a why to retrieve finish_reason
huggingface -> not sure finish_reason works ok - we need to test

**Comment by LeonRuggiero** [comment]
Changes concerning model parameters merged in linked PR.
