### ISSUE TITLE
Properly report token use count

### ISSUE THREAD

**Issue by ebarroca** [llumiverse/llumiverse#26]
We need to properly support reporting the token usage from the underlying provider, when executing a generation.

New token_usage standard meaning:
Old: character count
New: Reported token count or when streaming and nothing is reported, stream chunks are counted (treating each chunk as 1 token).

finish_reason: there should be no chunks after a stop signal i.e.:
null,null,null,null,null,stop

token_usage: tokens reported should be cumulative, not independent, i.e:
result tokens:
1,3,6,7,10,12 - represents chunks of length 1,2,3,1,3,2
1,2,3,4,5,6,7,8,9 - is common when streaming and the default when no counts are reported.
prompt tokens:
should be identical for each stream chunk

Some models do not support prompt token reporting, giving only result tokens.

**Comment by LeonRuggiero** [comment]
token usage support is merged in link PR.
